### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by kiemtcb** [laminair/jetson_stats_node_exporter#1]
Hello.
I am interested in your project. I have followed your instruction of installation. But I don't know how to run the program, could you tell more detail?

**Comment by laminair** [comment]
Thanks for the question.
You run the project simply as a python command: `python3 -m jetson_stats_node_exporter`. This will spawn a prometheus node exporter and you can scrape the statistics.
If you want to use the exporter as a background service: Put the command into a systemd service.

**Comment by kiemtcb** [comment]
Thank you for answering my question.
I did what you told but unfortunately i get a error:
`/usr/bin/python3:` No module named `jetson_prometheus_exporter`
I already run python3 setup install and still get that error when i run your command

> python3 -m jetson_stats_node_exporter
All commands i did with sudo. Therefore, how do i resolve this problem?

**Comment by kiemtcb** [comment]
Oh, thank you so much for answering my question.
I did what you said, and it works perfectly.
Thank you <3

**Comment by kiemtcb** [comment]
Thank you for answering my question
I did what you just said and it works perfectly.
Thank you <3

**Comment by balabala65535** [comment]
python3 -m jetson_stats_node_exporter
