### ISSUE TITLE
How can I infer the power threshold of the GPU from the power threshold of the CPU？

### ISSUE THREAD

**Issue by xiafengdongzhi** [laminair/jetson_stats_node_exporter#14]
In #13 the author mentions that：
 we use the device power consumption as a metric instead. We know the power threshold of the CPU and can infer the power threshold of the GPU based on the maximum total power draw of a jetson device, which provides you with all necessary information to calculate the device utilization.

But I don't know how to infer the power threshold of the GPU from the power threshold of the CPU.And If I want to express utilization in terms of power, do I want to divide the current power of the CPU and GPU by their maximum power respectively?
Thanks！

**Comment by xiafengdongzhi** [comment]
Is the GPU power threshold the total power minus the CPU power threshold?

**Comment by laminair** [comment]
Yes, this is one way to do it. The alternative is to fully saturate your device with a matrix multiplication on the GPU and observe the maximum power consumption of the GPU. The same goes for the CPU.
