### ISSUE TITLE
Not work service

### ISSUE THREAD

**Issue by DimIsaev** [laminair/jetson_stats_node_exporter#19]
Run

```bash
 python3 -m jetson_stats_node_exporter
 ```

Error
```bash

File "/home/jetson/jetson_stats_node_exporter/jetson_stats_node_exporter/exporter.py", line 117, in __emc
    emc_gauge.add_metric(["used"], value=self.jetson.jtop_stats["mem"]["EMC"]["max"])
KeyError: 'max'

```

**Comment by laminair** [comment]
I cannot reproduce this error. What's your stack? Jetson Stats version, node exporter version, python version? 
Can you report the full error trace?

**Comment by DimIsaev** [comment]
I am install 

``` bash
> git clone https://github.com/laminair/jetson_stats_node_exporter.git
> cd jetson_stats_node_exporter
> python3 setup.py install
```
Stack:  
Jetson NANO B01
Python 3.6 
Node exporter  1.8.2

**Comment by DimIsaev** [comment]
> Хорошо, Nano не имеет устройства хранения EMC.



> Ok, the Nano does not have an EMC storage device. Instead, it operates on an SD Card.

Not good

you draw conclusions without knowing the specification of the device

Nano has an EMC  and  SD card

![image](https://github.com/user-attachments/assets/22ca853e-b9b0-4782-aa8e-b349336d36b9)



I consider the proposal of forkunt project as a rude refusal
thank you, I will find another project
