### ISSUE TITLE
❓ Does `--update_period` actually do anything?

### ISSUE THREAD

**Issue by rernst76** [laminair/jetson_stats_node_exporter#4]
Hi!

Thanks for making this! I have been playing around with it and it works well!

I am confused about the `update_period` argument. It defaults to 10s, but from what I can tell, this argument doesn't serve any purpose.

It is possible one of my assumptions about how this works is wrong. Here is what I see:
- `update_period` defaults to 10 but can be provided as an arg via CLI
- `update_period` is provided as the `interval` setting for `JetsonExporter`
- `interval` is then used as the interval for constructing the `Jetson` object
- **then the user-provided `interval` is discarded [here](https://github.com/laminair/jetson_stats_node_exporter/blob/9123838ab7f1b1dd1b9fa76a587f1d579763d1fa/jetson_stats_node_exporter/exporter.py#L12) where we create a `JtopObservable` with `interval=0.5`**

Would it make sense to remove the `update_period` argument? 

Also, from what I can tell the default interval used by the `jtop service` is 1 second, not 500ms. When I launch jtop after starting `jetson_stats_node_exporter` I see a warning in the jtop GUI that says:
```
I CANNOT SET SPEED AT 1000ms - SERVER AT 500ms
```

I can confirm this by tailing the `jtop.service` logs and can see a message about the timer thread being set to 1000ms when I run jtop GUI; then I can see another thread about the timer thread being set to 500ms when I start `jetson_stats_node_exporter`.

It seems to me that you could consider either of:
- Remove the `update_period` arg and change the hard-coded `interval` value to 1s to avoid clashing with jtop default interval
- Remove the hard-coded `interval` value and keep `update_period` such that it is a useful argument

I think this default interval value is set [here](https://github.com/rbonghi/jetson_stats/blob/a5c3e4b0e25f62b9459c106666a681750e7620e8/jtop/service.py#L323).

**Comment by laminair** [comment]
Hi @rernst76 , 

Thanks for pointing this out. I missed that artifact.
The update period setting is fixed now. A new version is also available on PyPi. 

Please close the issue if things are working fine for you with the new version.

**Comment by rernst76** [comment]
Looks good. Thanks for fixing this!
